# Generated by Django 5.0.12 on 2025-02-06 07:59

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("makeup", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificate",
            name="cert_image",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="portfolio_image",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="artist_image",
        ),
        migrations.AddField(
            model_name="certificate",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="makeup/certifications/"),
        ),
        migrations.AddField(
            model_name="makeupartist",
            name="image",
            field=models.ImageField(
                default=datetime.datetime(2025, 2, 6, 7, 59, 32, 461959, tzinfo=datetime.timezone.utc),
                upload_to="makeup/",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portfolio",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="makeup/portfolios/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="makeup/artists/"),
        ),
    ]
